name: app_empresa
description: "Aplicación de Reservas para restaurantes La Leña"
publish_to: 'none'
version: 0.13.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_database: ^12.0.3
  share_plus: ^12.0.1
  csv: ^6.0.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  firebase_auth: ^6.1.1
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2 
  image_picker: ^1.0.7
  flutter_admin_scaffold: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/lalenaLogoV2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/iconLogo.png
    - assets/images/chickenLoading.png
    - assets/images/whatsapp.png
